server:
  port: 9923
spring:
  application:
    name: dormitory
  data:
    mongodb:
#      uri = 'mongodb://localhost:27017/EDUCATION
      uri: mongodb+srv://niyobethel:GCSsTx0qpEWjvW4z@bethel22.ycywdha.mongodb.net/EDUCATION?retryWrites=true&w=majority&appName=Bethel22